### ISSUE TITLE
Feature: CalDAV support

### ISSUE THREAD

**Issue by mokkin** [tekhnee/appointments#1]
Thanks to https://github.com/SergeyMosin/Appointments/issues/25#issuecomment-611527881 I noticed about your nice fork. Until about one month ago it looked like EasyAppointments development hast stopped, but now the author has come back with many commits.
The feature request of CalDAV support is already in EasyAppointments.

Are you planning this?

**Comment by yrammos** [comment]
@mokkin would you care to elaborate? What exactly is the feature you have in mind? Like the original app, this fork syncs bidirectionally with Google Calendar using the Google API, which is distinct from CalDAV.

**Comment by mokkin** [comment]
I know about the Google Sync.
Because of data protection reasons we do not want and cannot use Google. Therefore an alternative way for synchronizing calendars should be implemented such as CalDAV. CalDAV is used by big projects such as Nextcloud/Owncloud but also proprietary companies like Apple.

**Comment by tekhnee** [comment]
@mokkin we do not have plans to add CalDAV support, unless the upstream package (EasyAppointments) implements it in a sufficiently modular way for us to cherry-pick it from their repo. Sorry — this is a side-project for us and we prioritize features that we need imminently in our workshop.
